[options]
HoldPkg     = pacman glibc
Architecture = x86_64
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# NEUTRALIZAR LA DETECCIÓN AUTOMÁTICA DE CPUs MODERNOS
NoExtract = usr/share/libalpm/hooks/*cachyos*.hook
NoExtract = usr/bin/cachyos-repo

# REPOSITORIOS GENÉRICOS (Prohibido usar las versiones v3 o v4)
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
